
<div class="page-title">
    <h1><?php echo $this->__('Your BITCOIN order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php
// a little code here, sorry for that. @community, feel free to move this

$quote_id = $this->getRequest()->getParam('quote_id');

$btc = floatval($this->getRequest()->getParam('satoshi'))/100000000;
$btc = number_format($btc,8,'.','');
$quote = Mage::getModel('sales/quote')->load($quote_id);
$orders = Mage::getModel('sales/order')->getCollection()->addFieldToFilter('quote_id',$quote_id);
$order = null;
$error = 0;
$_btc = Mage::getModel('btcpay/btcpay')->load($quote_id);
$address = $_btc->getAddress();
foreach ($orders as $_order){
	$order = $_order;
	//this loop only loops once
}
if ($order != null) {
	$order = Mage::getModel('sales/order')->load($order->getId());
	echo $order->getIncrementId();
	echo '<br />Please transfer <b>'.$btc.'</b> BTC to <br />';
	echo $address;
	echo '<br />';
	// using google for qr code generation. Later bitcoincenter will provide qr code itself
	echo '<img src="https://chart.googleapis.com/chart?chs=400x400&chl='.$address.'&cht=qr" title="Bitcoin address" />';
	
	
} else {
	$error++;
	//smth. went wrong
}


?>



  


<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
